name: Build firmwares

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    name: Build firmware
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Initialize containers
        run: echo "Initializing build containers..."

      - name: Install SDK extensions
        run: |
          echo "Installing Silicon Labs SDK components..."

      # Исправление ошибки с правами репозитория внутри Docker (dubious ownership)
      - name: Fix Git safe directory
        run: git config --global --add safe.directory '*'

      # Основной запуск компиляции вашей прошивки с указанием файла конфигурации
      - name: Build firmware
        run: python3 tools/build_project.py --manifest dsgw280.yaml

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: firmware-binaries
          path: artifacts/
